services:
  tailscale-pi-hole:
    image: tailscale/tailscale:latest
    container_name: tailscale-pi-hole
    hostname: pi-hole
    environment:
      - TS_AUTHKEY=<TAILSCALE_AUTH_KEY>
      - "TS_EXTRA_ARGS=--advertise-tags=tag:node --reset"
      - TS_SERVE_CONFIG=/config/pi-hole.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: service:tailscale-pi-hole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Stockholm'
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - pihole_data:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

volumes:
  pihole_data:
    driver: local
  tailscale-pi-hole:
    driver: local

