---
- name: Maintenance
  hosts: night_tower
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 # Cache for one hour

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        name: "*"
        state: present
        upgrade: full
        autoclean: true
        autoremove: true
      register: apt_update_results

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server if a new kernel was installed
      ansible.builtin.reboot:
        msg: "Rebooting due to kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        post_reboot_delay: 30
      when: reboot_required_file.stat.exists
